# -*- coding: utf-8 -*-
"""microLANGAtone Concept Registro FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u49O4EbVGs9FG3rAX3H1NKFm98YEhAP5
"""



from IPython.display import HTML

pantalla_html = """
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>micro-LANGA-tone</title>
    <style>
        body {
            background-color: #000000;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .chord-btn {
            padding: 6px 10px;
            background: #141414;
            color: #ffffff;
            border: 1px solid #2a2a2a;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
            cursor: pointer;
            transition: all 0.15s ease;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 2px;
        }
        .chord-btn:hover { background: #222222; }
        .chord-btn.active {
            background: #d97706; /* Naranja sobrio */
            border-color: #f59e0b;
            color: #000000;
            box-shadow: 0 0 8px rgba(217,119,6,0.4);
        }
        .key-badge {
            font-size: 8px;
            color: #38bdf8; /* Azul sobrio */
            background: rgba(255,255,255,0.06);
            padding: 1px 4px;
            border-radius: 3px;
        }
        .looper-btn {
            padding: 6px 12px;
            background: #141414;
            color: #ffffff;
            border: 1px solid #2a2a2a;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
            cursor: pointer;
            transition: all 0.2s;
        }
        .looper-btn.rec-active {
            background: #b91c1c; /* Rojo grabación sobrio */
            border-color: #ef4444;
            color: #ffffff;
            box-shadow: 0 0 8px rgba(185,28,28,0.5);
            animation: pulse 1s infinite;
        }
        .looper-btn.play-active {
            background: #16a34a; /* Verde sobrio */
            border-color: #22c55e;
            color: #ffffff;
            box-shadow: 0 0 8px rgba(22,163,74,0.5);
        }
        @keyframes pulse {
            0% { opacity: 1; }
            50% { opacity: 0.6; }
            100% { opacity: 1; }
        }
    </style>
</head>
<body>

<div style="text-align: center; font-family: system-ui, -apple-system, sans-serif; padding: 15px; background: #0a0a0a; border-radius: 12px; width: 98%; max-width: 1800px; margin: auto; box-shadow: 0 8px 30px rgba(0,0,0,0.9); color: #ffffff; box-sizing: border-box; border: 1px solid #1a1a1a;">
    <!-- Título en Naranja -->
    <h2 style="color: #16a34a; margin-top: 0; margin-bottom: 12px; font-weight: 700; letter-spacing: 1px;">micro-LANGA-tone</h2>

    <!-- Panel Superior de Control de Acordes y Volumen -->
    <div style="background: #121212; padding: 12px 16px; border-radius: 8px; margin-bottom: 10px; display: flex; flex-wrap: wrap; gap: 12px; justify-content: space-between; align-items: center; border: 1px solid #222222;">

        <!-- Tónica y Controles de Octava Independientes -->
        <div style="display: flex; gap: 10px; align-items: center; flex-wrap: wrap;">
            <div>
                <label style="font-size: 10px; display: block; margin-bottom: 4px; color: #888888; font-weight: bold;">MELO TONE</label>
                <select id="rootSelect" onchange="updateChord()" style="padding: 5px 8px; background: #1a1a1a; color: #ffffff; border: 1px solid #333333; border-radius: 4px; font-weight: bold; cursor: pointer; outline: none;">
                    <option value="C">C [0]</option>
                    <option value="C#">C# [1]</option>
                    <option value="D">D [2]</option>
                    <option value="D#">D# [3]</option>
                    <option value="E">E [4]</option>
                    <option value="F">F [5]</option>
                    <option value="F#">F# [6]</option>
                    <option value="G">G [7]</option>
                    <option value="G#">G# [8]</option>
                    <option value="A" selected>A [9]</option>
                    <option value="A#">A# [=]</option>
                    <option value="B">B [/]</option>
                </select>
            </div>

            <!-- Octava para Teclas/Notas (Azul) -->
            <div>
                <label style="font-size: 10px; display: block; margin-bottom: 4px; color: #38bdf8; font-weight: bold;">MELO OCT</label>
                <div style="display: flex; gap: 2px; align-items: center;">
                    <button onclick="changeKeysOctave(-1)" style="padding: 3px 8px; background: #1a1a1a; color: #ffffff; border: 1px solid #333333; border-radius: 3px; cursor: pointer; font-weight: bold;">-</button>
                    <div id="octaveKeysDisplay" style="padding: 4px 8px; background: #141414; color: #38bdf8; border: 1px solid #333333; border-radius: 4px; font-weight: bold; min-width: 22px; text-align: center;">4</div>
                    <button onclick="changeKeysOctave(1)" style="padding: 3px 8px; background: #1a1a1a; color: #ffffff; border: 1px solid #333333; border-radius: 3px; cursor: pointer; font-weight: bold;">+</button>
                </div>
            </div>

            <!-- Octava para Acordes (Naranja) -->
            <div>
                <label style="font-size: 10px; display: block; margin-bottom: 4px; color: #d97706; font-weight: bold;">CHORD OCT</label>
                <div style="display: flex; gap: 2px; align-items: center;">
                    <button onclick="changeChordOctave(-1)" style="padding: 3px 8px; background: #1a1a1a; color: #ffffff; border: 1px solid #333333; border-radius: 3px; cursor: pointer; font-weight: bold;">-</button>
                    <div id="octaveChordDisplay" style="padding: 4px 8px; background: #141414; color: #d97706; border: 1px solid #333333; border-radius: 4px; font-weight: bold; min-width: 22px; text-align: center;">4</div>
                    <button onclick="changeChordOctave(1)" style="padding: 3px 8px; background: #1a1a1a; color: #ffffff; border: 1px solid #333333; border-radius: 3px; cursor: pointer; font-weight: bold;">+</button>
                </div>
            </div>

            <!-- Botón Toggle: Teclas cambian Tónica de Acorde -->
            <div>
                <label style="font-size: 10px; display: block; margin-bottom: 4px; color: #888888; font-weight: bold;">CHORD->MELO</label>
                <button id="btnKeyChord" onclick="toggleKeyChordMode()" style="padding: 6px 10px; background: #1a1a1a; color: #888888; border: 1px solid #333333; border-radius: 4px; font-size: 11px; font-weight: bold; cursor: pointer; transition: all 0.2s;">OFF</button>
            </div>

            <!-- Botón Toggle: Focus Zoom Acordes (Verde) -->
            <div>
                <label style="font-size: 10px; display: block; margin-bottom: 4px; color: #16a34a; font-weight: bold;">FOCUS ZOOM</label>
                <button id="btnFocusZoom" onclick="toggleFocusZoomMode()" style="padding: 6px 10px; background: #16a34a; color: #ffffff; border: 1px solid #22c55e; border-radius: 4px; font-size: 11px; font-weight: bold; cursor: pointer; transition: all 0.2s;">ON</button>
            </div>

            <!-- Botón de Parada Global -->
            <div>
                <label style="font-size: 10px; display: block; margin-bottom: 4px; color: #ef4444; font-weight: bold;">SPACEBAR</label>
                <button onclick="stopAll()" style="padding: 6px 12px; background: #261111; color: #ef4444; border: 1px solid #7f1d1d; border-radius: 4px; font-size: 11px; font-weight: bold; cursor: pointer; transition: background 0.2s;">STOP ALL</button>
            </div>
        </div>

        <!-- Botones de Acordes accionados por ZXCVBNM -->
        <div style="display: flex; gap: 5px; flex-wrap: wrap; justify-content: center;">
            <button class="chord-btn" onclick="toggleChord('dom7')" id="btn-dom7">Dom7 <span class="key-badge">Z</span></button>
            <button class="chord-btn" onclick="toggleChord('major')" id="btn-major">Major <span class="key-badge">X</span></button>
            <button class="chord-btn" onclick="toggleChord('min7')" id="btn-min7">minor 7 <span class="key-badge">C</span></button>
            <button class="chord-btn" onclick="toggleChord('maj7')" id="btn-maj7">Maj7 <span class="key-badge">V</span></button>
            <button class="chord-btn" onclick="toggleChord('min6')" id="btn-min6">minor 6 <span class="key-badge">B</span></button>
            <button class="chord-btn" onclick="toggleChord('maj6')" id="btn-maj6">Major 6 <span class="key-badge">N</span></button>
            <button class="chord-btn" onclick="toggleChord('dim7')" id="btn-dim7">dim7 <span class="key-badge">M</span></button>
        </div>

        <!-- Controles de Volumen, Cents y Reverb De La Tere -->
        <div style="display: flex; gap: 12px; border-left: 1px solid #222222; padding-left: 12px; align-items: center; flex-wrap: wrap;">
            <div>
                <label style="font-size: 9px; display: block; color: #38bdf8; font-weight: bold;">VOL MEL [↑/↓]</label>
                <input type="range" id="volTheremin" min="0" max="1" step="0.01" value="0.8" style="width: 55px; cursor: pointer;">
            </div>

            <div>
                <label style="font-size: 9px; display: block; color: #38bdf8; font-weight: bold;">MELO CENTS (<span id="meloCentsVal">0</span>)</label>
                <input type="range" id="meloCents" min="-100" max="100" step="1" value="0" oninput="updateMeloCents()" onclick="handleCentsClick(event, 'meloCents')" style="width: 65px; cursor: pointer;" title="Option/Alt + Click para restablecer a 0">
            </div>

            <div>
                <label style="font-size: 9px; display: block; color: #d97706; font-weight: bold;">CHORD VOL [←/→]</label>
                <input type="range" id="volChord" min="0" max="1" step="0.01" value="0.6" oninput="updateChordVolume()" style="width: 55px; cursor: pointer;">
            </div>

            <div>
                <label style="font-size: 9px; display: block; color: #16a34a; font-weight: bold;">Reverb De La Tere</label>
                <input type="range" id="reverbWet" min="0" max="1" step="0.01" value="0.35" oninput="updateReverbWet()" style="width: 55px; cursor: pointer;">
            </div>
        </div>
    </div>

    <!-- Panel de CHORD LOOPER -->
    <div style="background: #121212; padding: 10px 15px; border-radius: 8px; margin-bottom: 10px; display: flex; flex-wrap: wrap; gap: 15px; justify-content: space-between; align-items: center; border: 1px solid #2a1f12;">
        <div style="display: flex; gap: 10px; align-items: center; flex-wrap: wrap;">
            <span style="color: #d97706; font-weight: bold; font-size: 12px;">CHORD LOOPER:</span>
            <button id="btnRecLoop" onclick="toggleRecordLoop()" class="looper-btn">● REC [NUMPAD ENTER]</button>
            <button id="btnPlayLoop" onclick="togglePlayLoop()" class="looper-btn">▶ PLAY LOOP [ENTER]</button>
            <button onclick="clearLoop()" class="looper-btn" style="background: #1a1a1a; color: #aaa;">CLEAR</button>

            <div style="display: flex; align-items: center; gap: 6px; margin-left: 10px; border-left: 1px solid #222222; padding-left: 10px;">
                <label style="font-size: 10px; color: #d97706; font-weight: bold;">LOOP CENTS (<span id="loopCentsVal">0</span>):</label>
                <input type="range" id="loopCents" min="-100" max="100" step="1" value="0" oninput="updateLoopCents()" onclick="handleCentsClick(event, 'loopCents')" style="width: 80px; cursor: pointer;" title="Option/Alt + Click para restablecer a 0">
            </div>
        </div>

        <div style="display: flex; gap: 15px; align-items: center;">
            <div id="looperStatus" style="font-size: 11px; color: #888888; font-weight: bold;">Estado: Listo (Vacío)</div>
        </div>
    </div>

    <!-- Panel de EFECTOS GENERALES DE SALIDA -->
    <div style="background: #121212; padding: 8px 15px; border-radius: 8px; margin-bottom: 10px; display: flex; flex-wrap: wrap; gap: 18px; justify-content: center; align-items: center; border: 1px solid #1a1a24;">
        <span style="color: #38bdf8; font-weight: bold; font-size: 11px; letter-spacing: 0.5px;">MASTER FX:</span>

        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="font-size: 10px; color: #d97706; font-weight: bold;">SATURATION:</label>
            <input type="range" id="fxDistortion" min="0" max="100" step="1" value="0" oninput="updateMasterFX()" style="width: 80px; cursor: pointer;">
            <span id="distVal" style="font-size: 10px; color: #888; width: 25px;">0%</span>
        </div>

        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="font-size: 10px; color: #38bdf8; font-weight: bold;">FLANGER WET:</label>
            <input type="range" id="fxFlangerWet" min="0" max="1" step="0.01" value="0" oninput="updateMasterFX()" style="width: 80px; cursor: pointer;">
            <span id="flangWetVal" style="font-size: 10px; color: #888; width: 28px;">0%</span>
        </div>

        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="font-size: 10px; color: #38bdf8; font-weight: bold;">FLANGER RATE:</label>
            <input type="range" id="fxFlangerRate" min="0.1" max="5" step="0.1" value="0.5" oninput="updateMasterFX()" style="width: 70px; cursor: pointer;">
            <span id="flangRateVal" style="font-size: 10px; color: #888; width: 32px;">0.5Hz</span>
        </div>

        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="font-size: 10px; color: #16a34a; font-weight: bold;">MASTER REVERB:</label>
            <input type="range" id="fxMasterReverb" min="0" max="1" step="0.01" value="0" oninput="updateMasterFX()" style="width: 80px; cursor: pointer;">
            <span id="masterReverbVal" style="font-size: 10px; color: #888; width: 28px;">0%</span>
        </div>

        <div style="display: flex; align-items: center; gap: 8px; border-left: 1px solid #222222; padding-left: 12px;">
            <label style="font-size: 10px; color: #16a34a; font-weight: bold;">MASTER VOL:</label>
            <input type="range" id="fxMasterVol" min="0" max="1.5" step="0.01" value="1.0" oninput="updateMasterFX()" style="width: 80px; cursor: pointer;">
            <span id="masterVolVal" style="font-size: 10px; color: #888; width: 32px;">100%</span>
        </div>
    </div>

    <!-- Panel de Zoom X/Y -->
    <div style="background: #121212; padding: 8px 15px; border-radius: 8px; margin-bottom: 10px; display: flex; flex-wrap: wrap; gap: 18px; justify-content: center; align-items: center; border: 1px solid #1a1a1a;">
        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="font-size: 11px; color: #38bdf8; font-weight: bold;">ZOOM X (Scroll):</label>
            <input type="range" id="zoomX" min="1" max="10" step="0.1" value="1.0" oninput="onZoomChange()" style="width: 120px; cursor: pointer;">
            <span id="zoomXVal" style="font-size: 11px; color: #888; width: 32px;">1.0x</span>
        </div>

        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="font-size: 11px; color: #d97706; font-weight: bold;">X POSITION:</label>
            <input type="range" id="offsetX" min="0" max="1" step="0.001" value="0" disabled oninput="triggerRedraw()" style="width: 140px; cursor: pointer;">
        </div>

        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="font-size: 11px; color: #16a34a; font-weight: bold;">ZOOM Y:</label>
            <input type="range" id="zoomY" min="0.5" max="5" step="0.1" value="1" oninput="onZoomChange()" style="width: 120px; cursor: pointer;">
            <span id="zoomYVal" style="font-size: 11px; color: #888; width: 32px;">1.0x</span>
        </div>

        <button onclick="resetZoom()" style="padding: 4px 10px; background: #1a1a1a; color: #fff; border: 1px solid #333; border-radius: 4px; font-size: 10px; font-weight: bold; cursor: pointer;">Zoom Reset</button>
    </div>

    <!-- Pantalla Theremin -->
    <canvas id="screen" width="1800" height="480" style="background: #000000; border-radius: 6px; width: 100%; height: 480px; cursor: crosshair; display: block; margin: auto; border: 1px solid #1a1a1a;"></canvas>

    <!-- Texto Inferior + Créditos en Naranja -->
    <div id="info" style="color: #888888; font-size: 13px; margin-top: 8px; font-weight: 500;">Pad Numérico: [0=C, 1=C#, 2=D, 3=D#, 4=E, 5=F, 6=F#, 7=G, 8=G#, 9=A, ==A#, /=B, *=Oct+, Enter=REC]</div>
    <div style="color: #d97706; font-size: 11px; margin-top: 6px; font-weight: 700; letter-spacing: 1.5px; opacity: 0.9;">by Langalab Design</div>
</div>

<script>
const audioCtx = new (window.AudioContext || window.webkitAudioContext)();

window.addEventListener('click', () => {
    if (audioCtx.state === 'suspended') {
        audioCtx.resume();
    }
}, { once: true });

// --- RED DE AUDIO GLOBAL, MASTER VOL Y EFECTOS ---
const masterInputBus = audioCtx.createGain();

const distNode = audioCtx.createWaveShaper();
function makeSoftSaturationCurve(amount) {
    let n_samples = 44100,
        curve = new Float32Array(n_samples),
        i = 0, x;
    let drive = 1 + (amount / 100) * 3;
    for (; i < n_samples; ++i) {
        x = i * 2 / n_samples - 1;
        curve[i] = Math.tanh(x * drive);
    }
    return curve;
}
distNode.curve = makeSoftSaturationCurve(0);
distNode.oversample = '4x';

const flangerDryGain = audioCtx.createGain();
const flangerWetGain = audioCtx.createGain();
const flangerDelay = audioCtx.createDelay();
flangerDelay.delayTime.value = 0.005;

const flangerLFO = audioCtx.createOscillator();
const flangerLFOGain = audioCtx.createGain();
flangerLFO.type = 'sine';
flangerLFO.frequency.value = 0.5;
flangerLFOGain.gain.value = 0.002;

flangerLFO.connect(flangerLFOGain);
flangerLFOGain.connect(flangerDelay.delayTime);
flangerLFO.start();

const masterReverbDryNode = audioCtx.createGain();
const masterReverbWetNode = audioCtx.createGain();
const masterDelayTimes = [0.031, 0.043, 0.057, 0.071];
const masterDelayNodes = masterDelayTimes.map(t => {
    const d = audioCtx.createDelay();
    d.delayTime.value = t;
    return d;
});
const masterFeedbackGain = audioCtx.createGain();
masterFeedbackGain.gain.value = 0.7;

const masterLowpassFilter = audioCtx.createBiquadFilter();
masterLowpassFilter.type = 'lowpass';
masterLowpassFilter.frequency.value = 2500;

const masterVolumeNode = audioCtx.createGain();

masterInputBus.connect(distNode);
distNode.connect(flangerDryGain);
distNode.connect(flangerDelay);
flangerDelay.connect(flangerWetGain);

const fxOutBus = audioCtx.createGain();
flangerDryGain.connect(fxOutBus);
flangerWetGain.connect(fxOutBus);

const dryGainNode = audioCtx.createGain();
const wetGainNode = audioCtx.createGain();
const delayTimes = [0.029, 0.037, 0.041, 0.053];
const delayNodes = delayTimes.map(t => {
    const d = audioCtx.createDelay();
    d.delayTime.value = t;
    return d;
});
const feedbackGain = audioCtx.createGain();
feedbackGain.gain.value = 0.65;

const lowpassFilter = audioCtx.createBiquadFilter();
lowpassFilter.type = 'lowpass';
lowpassFilter.frequency.value = 3000;

fxOutBus.connect(dryGainNode);
delayNodes.forEach(d => {
    fxOutBus.connect(d);
    d.connect(lowpassFilter);
});
lowpassFilter.connect(feedbackGain);
feedbackGain.connect(delayNodes[0]);
feedbackGain.connect(wetGainNode);

const reverb1Out = audioCtx.createGain();
dryGainNode.connect(reverb1Out);
wetGainNode.connect(reverb1Out);

reverb1Out.connect(masterReverbDryNode);
masterDelayNodes.forEach(d => {
    reverb1Out.connect(d);
    d.connect(masterLowpassFilter);
});
masterLowpassFilter.connect(masterFeedbackGain);
masterFeedbackGain.connect(masterDelayNodes[0]);
masterFeedbackGain.connect(masterReverbWetNode);

masterReverbDryNode.connect(masterVolumeNode);
masterReverbWetNode.connect(masterVolumeNode);
masterVolumeNode.connect(audioCtx.destination);

function updateMasterFX() {
    const distAmount = parseFloat(document.getElementById('fxDistortion').value);
    const flangWet = parseFloat(document.getElementById('fxFlangerWet').value);
    const flangRate = parseFloat(document.getElementById('fxFlangerRate').value);
    const masterRev = parseFloat(document.getElementById('fxMasterReverb').value);
    const masterVol = parseFloat(document.getElementById('fxMasterVol').value);

    document.getElementById('distVal').innerText = distAmount + '%';
    document.getElementById('flangWetVal').innerText = Math.round(flangWet * 100) + '%';
    document.getElementById('flangRateVal').innerText = flangRate.toFixed(1) + 'Hz';
    document.getElementById('masterReverbVal').innerText = Math.round(masterRev * 100) + '%';
    document.getElementById('masterVolVal').innerText = Math.round(masterVol * 100) + '%';

    distNode.curve = makeSoftSaturationCurve(distAmount);
    flangerWetGain.gain.setTargetAtTime(flangWet, audioCtx.currentTime, 0.02);
    flangerDryGain.gain.setTargetAtTime(1 - (flangWet * 0.3), audioCtx.currentTime, 0.02);
    flangerLFO.frequency.setTargetAtTime(flangRate, audioCtx.currentTime, 0.02);

    masterReverbWetNode.gain.setTargetAtTime(masterRev, audioCtx.currentTime, 0.02);
    masterReverbDryNode.gain.setTargetAtTime(1 - (masterRev * 0.5), audioCtx.currentTime, 0.02);

    masterVolumeNode.gain.setTargetAtTime(masterVol, audioCtx.currentTime, 0.02);
}

function updateReverbWet() {
    const wetVal = parseFloat(document.getElementById('reverbWet').value);
    wetGainNode.gain.setValueAtTime(wetVal, audioCtx.currentTime);
    dryGainNode.gain.setValueAtTime(1 - (wetVal * 0.5), audioCtx.currentTime);
}
updateReverbWet();

const canvas = document.getElementById('screen');
const ctx = canvas.getContext('2d');
const info = document.getElementById('info');

const minFreq = 440 * Math.pow(2, (12 - 69) / 12);
const maxFreq = 440 * Math.pow(2, (131 - 69) / 12);

const noteNames = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

const chordIntervals = {
    'dom7':  [0, 4, 7, 10],
    'major': [0, 4, 7],
    'min7':  [0, 3, 7, 10],
    'maj7':  [0, 4, 7, 11],
    'min6':  [0, 3, 7, 9],
    'maj6':  [0, 4, 7, 9],
    'dim7':  [0, 3, 6, 9]
};

const keyToChordMap = {
    'z': 'dom7', 'x': 'major', 'c': 'min7', 'v': 'maj7',
    'b': 'min6', 'n': 'maj6', 'm': 'dim7'
};

const customNumpadMap = {
    '0': 'C', '1': 'C#', '2': 'D', '3': 'D#', '4': 'E', '5': 'F',
    '6': 'F#', '7': 'G', '8': 'G#', '9': 'A', '=': 'A#', '/': 'B'
};

const keyboardPianoMap = {
    'a': { note: 'C', octaveOffset: 0 },
    'w': { note: 'C#', octaveOffset: 0 },
    's': { note: 'D', octaveOffset: 0 },
    'e': { note: 'D#', octaveOffset: 0 },
    'd': { note: 'E', octaveOffset: 0 },
    'f': { note: 'F', octaveOffset: 0 },
    't': { note: 'F#', octaveOffset: 0 },
    'g': { note: 'G', octaveOffset: 0 },
    'y': { note: 'G#', octaveOffset: 0 },
    'h': { note: 'A', octaveOffset: 0 },
    'u': { note: 'A#', octaveOffset: 0 },
    'j': { note: 'B', octaveOffset: 0 },
    'k': { note: 'C', octaveOffset: 1 },
    'o': { note: 'C#', octaveOffset: 1 },
    'l': { note: 'D', octaveOffset: 1 },
    'p': { note: 'D#', octaveOffset: 1 },
    'ñ': { note: 'E', octaveOffset: 1 },
    '`': { note: 'F', octaveOffset: 1 }
};

let keysOctave = 4;
let chordOctave = 4;
let keyFollowsChord = false;
let focusZoomEnabled = true;

function handleCentsClick(e, sliderId) {
    if (e.altKey) {
        const slider = document.getElementById(sliderId);
        slider.value = 0;
        if (sliderId === 'meloCents') updateMeloCents();
        if (sliderId === 'loopCents') updateLoopCents();
    }
}

function updateMeloCents() {
    const cents = parseFloat(document.getElementById('meloCents').value);
    document.getElementById('meloCentsVal').innerText = cents;
    Object.keys(activeVoices).forEach(id => {
        if (activeVoices[id].osc) {
            activeVoices[id].osc.detune.setTargetAtTime(cents, audioCtx.currentTime, 0.01);
        }
    });
}

function updateLoopCents() {
    const cents = parseFloat(document.getElementById('loopCents').value);
    document.getElementById('loopCentsVal').innerText = cents;
    chordVoices.forEach(v => {
        if (v.osc && v.isFromLoop) {
            v.osc.detune.setTargetAtTime(cents, audioCtx.currentTime, 0.01);
        }
    });
}

let loopEvents = [];
let isRecording = false;
let isPlayingLoop = false;
let recStartTime = 0;
let loopDuration = 0;
let loopTimer = null;
let loopPlaybackTimeouts = [];

function toggleRecordLoop() {
    if (isRecording) {
        stopRecordingLoop();
        if (loopEvents.length > 0) {
            togglePlayLoop();
        }
    } else {
        startRecordingLoop();
    }
}

function startRecordingLoop() {
    if (isPlayingLoop) stopLoopPlayback();
    loopEvents = [];
    isRecording = true;
    recStartTime = audioCtx.currentTime;
    document.getElementById('btnRecLoop').classList.add('rec-active');
    document.getElementById('btnRecLoop').innerText = '■ STOP REC [NUMPAD ENTER]';
    document.getElementById('looperStatus').innerText = 'Estado: Grabando acordes...';
}

function stopRecordingLoop() {
    if (!isRecording) return;
    isRecording = false;
    document.getElementById('btnRecLoop').classList.remove('rec-active');
    document.getElementById('btnRecLoop').innerText = '● REC [NUMPAD ENTER]';
    loopDuration = audioCtx.currentTime - recStartTime;

    if (loopEvents.length === 0) {
        document.getElementById('looperStatus').innerText = 'Estado: Grabación vacía';
    } else {
        document.getElementById('looperStatus').innerText = `Estado: Loop Grabado (${loopEvents.length} acordes, ${loopDuration.toFixed(1)}s)`;
    }
}

function recordChordEvent(root, chordType, oct) {
    if (!isRecording) return;
    const time = audioCtx.currentTime - recStartTime;
    loopEvents.push({ time, root, chordType, octave: oct });
}

function togglePlayLoop() {
    if (isPlayingLoop) {
        stopLoopPlayback();
    } else {
        if (isRecording) {
            stopRecordingLoop();
        }
        if (loopEvents.length === 0) return;

        isPlayingLoop = true;
        document.getElementById('btnPlayLoop').classList.add('play-active');
        document.getElementById('btnPlayLoop').innerText = '■ STOP LOOP [ENTER]';
        document.getElementById('looperStatus').innerText = 'Estado: Reproduciendo Loop 🔁';
        runLoopIteration();
    }
}

function runLoopIteration() {
    if (!isPlayingLoop) return;
    stopChord();

    loopEvents.forEach(evt => {
        const timeoutId = setTimeout(() => {
            if (!isPlayingLoop) return;
            document.getElementById('rootSelect').value = evt.root;
            chordOctave = evt.octave;
            document.getElementById('octaveChordDisplay').innerText = chordOctave;
            activeChordType = evt.chordType;
            playChord(false, true);
        }, evt.time * 1000);
        loopPlaybackTimeouts.push(timeoutId);
    });

    loopTimer = setTimeout(() => {
        if (isPlayingLoop) runLoopIteration();
    }, Math.max(1000, loopDuration * 1000));
}

function stopLoopPlayback() {
    isPlayingLoop = false;
    clearTimeout(loopTimer);
    loopPlaybackTimeouts.forEach(t => clearTimeout(t));
    loopPlaybackTimeouts = [];
    document.getElementById('btnPlayLoop').classList.remove('play-active');
    document.getElementById('btnPlayLoop').innerText = '▶ PLAY LOOP [ENTER]';
    document.getElementById('looperStatus').innerText = loopEvents.length > 0 ? 'Estado: Loop Pausado' : 'Estado: Listo (Vacío)';
    stopChord();
}

function clearLoop() {
    stopLoopPlayback();
    if (isRecording) stopRecordingLoop();
    loopEvents = [];
    loopDuration = 0;
    document.getElementById('looperStatus').innerText = 'Estado: Listo (Vacío)';
}

const notesList = [];
for (let octave = 0; octave <= 9; octave++) {
    noteNames.forEach((name, i) => {
        const midiNote = (octave + 1) * 12 + i;
        const freq = 440 * Math.pow(2, (midiNote - 69) / 12);
        const logMin = Math.log(minFreq);
        const logMax = Math.log(maxFreq);
        const xRatio = (Math.log(freq) - logMin) / (logMax - logMin);

        notesList.push({
            name: `${name}${octave}`,
            freq: freq,
            xRatio: xRatio,
            isBlack: name.includes('#'),
            isA440: name === 'A' && octave === 4
        });
    });
}

const activeVoices = {};
let activeChordType = null;
let chordVoices = [];
let hoverPos = { xRatio: -1, yRatio: -1, active: false };
let animFrameId = null;

function toggleKeyChordMode() {
    keyFollowsChord = !keyFollowsChord;
    const btn = document.getElementById('btnKeyChord');
    if (keyFollowsChord) {
        btn.innerText = "ON";
        btn.style.background = "#38bdf8";
        btn.style.color = "#000000";
    } else {
        btn.innerText = "OFF";
        btn.style.background = "#1a1a1a";
        btn.style.color = "#888888";
    }
}

function toggleFocusZoomMode() {
    focusZoomEnabled = !focusZoomEnabled;
    const btn = document.getElementById('btnFocusZoom');
    if (focusZoomEnabled) {
        btn.innerText = "ON";
        btn.style.background = "#16a34a";
        btn.style.color = "#ffffff";
        btn.style.borderColor = "#22c55e";
    } else {
        btn.innerText = "OFF";
        btn.style.background = "#1a1a1a";
        btn.style.color = "#888888";
        btn.style.borderColor = "#333333";
    }
}

function stopAll() {
    stopLoopPlayback();
    if (isRecording) stopRecordingLoop();
    stopChord();
    activeChordType = null;
    document.querySelectorAll('.chord-btn').forEach(btn => btn.classList.remove('active'));

    Object.keys(activeVoices).forEach(id => {
        stopVoice(id);
    });
    triggerRedraw();
}

function triggerRedraw() {
    if (!animFrameId) {
        animFrameId = requestAnimationFrame(loop);
    }
}

function loop() {
    draw();
    if (Object.keys(activeVoices).length > 0 || chordVoices.length > 0 || hoverPos.active) {
        animFrameId = requestAnimationFrame(loop);
    } else {
        animFrameId = null;
    }
}

function onZoomChange() {
    const zX = parseFloat(document.getElementById('zoomX').value);
    const zY = parseFloat(document.getElementById('zoomY').value);
    document.getElementById('zoomXVal').innerText = zX.toFixed(1) + 'x';
    document.getElementById('zoomYVal').innerText = zY.toFixed(1) + 'x';

    const offsetSlider = document.getElementById('offsetX');
    if (zX > 1) {
        offsetSlider.disabled = false;
        offsetSlider.max = (1 - (1 / zX)).toString();
    } else {
        offsetSlider.disabled = true;
        offsetSlider.value = "0";
    }
    triggerRedraw();
}

canvas.addEventListener('wheel', (e) => {
    e.preventDefault();
    const zoomInput = document.getElementById('zoomX');
    let currentZoom = parseFloat(zoomInput.value);

    if (e.deltaY < 0) {
        currentZoom = Math.min(10, currentZoom + 0.2);
    } else {
        currentZoom = Math.max(1, currentZoom - 0.2);
    }

    zoomInput.value = currentZoom.toFixed(1);
    onZoomChange();
}, { passive: false });

function resetZoom() {
    document.getElementById('zoomX').value = 1.0;
    document.getElementById('zoomY').value = 1;
    document.getElementById('offsetX').value = 0;
    onZoomChange();
}

function focusZoomOnChord(rootXRatio) {
    if (!focusZoomEnabled) return;

    const zX = parseFloat(document.getElementById('zoomX').value);
    if (zX <= 1) return;

    const offsetSlider = document.getElementById('offsetX');
    const visibleWidthRatio = 1 / zX;

    let targetOffset = rootXRatio - (visibleWidthRatio / 2);
    const maxOffset = 1 - visibleWidthRatio;

    targetOffset = Math.max(0, Math.min(maxOffset, targetOffset));
    offsetSlider.value = targetOffset;
}

function normToCanvasX(xNorm) {
    const zX = parseFloat(document.getElementById('zoomX').value);
    const offX = parseFloat(document.getElementById('offsetX').value);
    return (xNorm - offX) * zX * canvas.width;
}

function canvasToNormX(canvasX) {
    const zX = parseFloat(document.getElementById('zoomX').value);
    const offX = parseFloat(document.getElementById('offsetX').value);
    return (canvasX / (canvas.width * zX)) + offX;
}

function normToCanvasY(yNorm) {
    const zY = parseFloat(document.getElementById('zoomY').value);
    const centerY = canvas.height / 2;
    const rawY = canvas.height - (yNorm * canvas.height);
    return centerY + (rawY - centerY) * zY;
}

function canvasToNormY(canvasY) {
    const zY = parseFloat(document.getElementById('zoomY').value);
    const centerY = canvas.height / 2;
    const unscaledY = centerY + (canvasY - centerY) / zY;
    return Math.max(0, Math.min(1, 1 - (unscaledY / canvas.height)));
}

function toggleChord(type) {
    if (activeChordType === type) {
        stopChord();
        activeChordType = null;
    } else {
        activeChordType = type;
        playChord(true, false);
    }
    document.querySelectorAll('.chord-btn').forEach(btn => btn.classList.remove('active'));
    if (activeChordType) {
        document.getElementById(`btn-${activeChordType}`).classList.add('active');
    }
}

function updateChord() {
    if (activeChordType) playChord(true, isPlayingLoop);
}

function changeKeysOctave(delta) {
    const newOctave = keysOctave + delta;
    if (newOctave >= 0 && newOctave <= 9) {
        keysOctave = newOctave;
        document.getElementById('octaveKeysDisplay').innerText = keysOctave;
    }
}

function changeChordOctave(delta) {
    const newOctave = chordOctave + delta;
    if (newOctave >= 0 && newOctave <= 9) {
        chordOctave = newOctave;
        document.getElementById('octaveChordDisplay').innerText = chordOctave;
        if (activeChordType) playChord(true, isPlayingLoop);
    }
}

function playChord(allowRecord = true, isFromLoop = false) {
    stopChord();
    if (!activeChordType) return;
    if (audioCtx.state === 'suspended') audioCtx.resume();

    const rootNoteName = document.getElementById('rootSelect').value;
    if (allowRecord && isRecording) {
        recordChordEvent(rootNoteName, activeChordType, chordOctave);
    }

    const rootMIDI = noteNames.indexOf(rootNoteName) + (chordOctave + 1) * 12;
    const intervals = chordIntervals[activeChordType];
    const chordVolSlider = parseFloat(document.getElementById('volChord').value);

    const rootFreq = 440 * Math.pow(2, (rootMIDI - 69) / 12);
    const logMin = Math.log(minFreq);
    const logMax = Math.log(maxFreq);
    const rootXRatio = (Math.log(rootFreq) - logMin) / (logMax - logMin);

    focusZoomOnChord(rootXRatio);

    const loopCents = isFromLoop ? parseFloat(document.getElementById('loopCents').value) : 0;

    intervals.forEach(semitones => {
        const midi = rootMIDI + semitones;
        const freq = 440 * Math.pow(2, (midi - 69) / 12);

        const osc = audioCtx.createOscillator();
        const gain = audioCtx.createGain();

        osc.type = 'triangle';
        osc.frequency.setValueAtTime(freq, audioCtx.currentTime);
        if (isFromLoop) {
            osc.detune.setValueAtTime(loopCents, audioCtx.currentTime);
        }

        const volume = (chordVolSlider * 0.15);
        gain.gain.setValueAtTime(volume, audioCtx.currentTime);

        osc.connect(gain);
        gain.connect(masterInputBus);
        osc.start();

        const xRatio = (Math.log(freq) - logMin) / (logMax - logMin);
        chordVoices.push({ osc, gain, freq, xRatio, volume, isFromLoop });
    });
    triggerRedraw();
}

function stopChord() {
    const now = audioCtx.currentTime;
    chordVoices.forEach(v => {
        v.gain.gain.cancelScheduledValues(now);
        v.gain.gain.setValueAtTime(v.gain.gain.value, now);
        v.gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.08);
        setTimeout(() => { v.osc.stop(); v.osc.disconnect(); }, 90);
    });
    chordVoices = [];
    triggerRedraw();
}

function updateChordVolume() {
    const chordVolSlider = parseFloat(document.getElementById('volChord').value);
    chordVoices.forEach(v => {
        const volume = (chordVolSlider * 0.15);
        v.gain.gain.setTargetAtTime(volume, audioCtx.currentTime, 0.02);
    });
}

function adjustThereminVolume(delta) {
    const input = document.getElementById('volTheremin');
    let val = parseFloat(input.value) + delta;
    val = Math.max(0, Math.min(1, val));
    input.value = val.toFixed(2);
}

function adjustChordVolume(delta) {
    const input = document.getElementById('volChord');
    let val = parseFloat(input.value) + delta;
    val = Math.max(0, Math.min(1, val));
    input.value = val.toFixed(2);
    updateChordVolume();
}

function startVoice(id, xRatio, yRatio) {
    if (audioCtx.state === 'suspended') audioCtx.resume();

    const logMin = Math.log(minFreq);
    const logMax = Math.log(maxFreq);
    const freq = Math.exp(logMin + xRatio * (logMax - logMin));
    const mainVolSlider = parseFloat(document.getElementById('volTheremin').value);
    const meloCents = parseFloat(document.getElementById('meloCents').value);
    const volume = Math.max(0.0001, Math.min(1.0, yRatio)) * (mainVolSlider * 0.3);

    if (!activeVoices[id]) {
        const osc = audioCtx.createOscillator();
        const gain = audioCtx.createGain();

        osc.type = 'triangle';
        osc.frequency.setValueAtTime(freq, audioCtx.currentTime);
        osc.detune.setValueAtTime(meloCents, audioCtx.currentTime);
        gain.gain.setValueAtTime(volume, audioCtx.currentTime);

        osc.connect(gain);
        gain.connect(masterInputBus);
        osc.start();

        activeVoices[id] = { osc, gain, xRatio, yRatio, freq, volume };
    } else {
        const voice = activeVoices[id];
        voice.xRatio = xRatio;
        voice.yRatio = yRatio;
        voice.freq = freq;
        voice.volume = volume;
        voice.osc.frequency.setTargetAtTime(freq, audioCtx.currentTime, 0.02);
        voice.osc.detune.setTargetAtTime(meloCents, audioCtx.currentTime, 0.01);
        voice.gain.gain.setTargetAtTime(volume, audioCtx.currentTime, 0.02);
    }
    triggerRedraw();
}

function stopVoice(id) {
    if (activeVoices[id]) {
        const voice = activeVoices[id];
        const now = audioCtx.currentTime;
        voice.gain.gain.cancelScheduledValues(now);
        voice.gain.gain.setValueAtTime(voice.gain.gain.value, now);
        voice.gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.08);
        setTimeout(() => {
            if (voice.osc) { voice.osc.stop(); voice.osc.disconnect(); }
            delete activeVoices[id];
            triggerRedraw();
        }, 90);
    }
}

function getClosestNote(freq) {
    let closestNote = notesList[0];
    let minDiff = Math.abs(freq - notesList[0].freq);
    notesList.forEach(n => {
        const diff = Math.abs(freq - n.freq);
        if (diff < minDiff) { minDiff = diff; closestNote = n; }
    });
    return closestNote;
}

function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    const zY = parseFloat(document.getElementById('zoomY').value);

    notesList.forEach(note => {
        const x = normToCanvasX(note.xRatio);
        if (x < -10 || x > canvas.width + 10) return;

        if (note.isA440) {
            ctx.strokeStyle = '#d97706';
            ctx.lineWidth = 2;
            ctx.beginPath();
            ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height);
            ctx.stroke();

            ctx.fillStyle = '#d97706';
            ctx.font = 'bold 12px sans-serif';
            ctx.textAlign = 'center';
            ctx.fillText('A4 (440Hz)', x, 22);
        } else if (note.name.startsWith('C')) {
            ctx.strokeStyle = 'rgba(255, 255, 255, 0.25)';
            ctx.lineWidth = 1;
            ctx.beginPath();
            ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height);
            ctx.stroke();

            ctx.fillStyle = 'rgba(255, 255, 255, 0.7)';
            ctx.font = 'bold 11px sans-serif';
            ctx.textAlign = 'center';
            ctx.fillText(note.name, x, canvas.height - 10);
        } else if (!note.isBlack) {
            ctx.strokeStyle = 'rgba(255, 255, 255, 0.04)';
            ctx.lineWidth = 1;
            ctx.beginPath();
            ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height);
            ctx.stroke();
        }
    });

    chordVoices.forEach(v => {
        const x = normToCanvasX(v.xRatio);
        if (x < -10 || x > canvas.width + 10) return;

        ctx.strokeStyle = 'rgba(217, 119, 6, 0.5)';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height);
        ctx.stroke();

        ctx.fillStyle = '#d97706';
        ctx.beginPath();
        ctx.arc(x, canvas.height / 2, 6, 0, Math.PI * 2);
        ctx.fill();
    });

    if (hoverPos.active && !activeVoices['mouse']) {
        const hX = normToCanvasX(hoverPos.xRatio);
        const hY = normToCanvasY(hoverPos.yRatio);

        const logMin = Math.log(minFreq);
        const logMax = Math.log(maxFreq);
        const hoverFreq = Math.exp(logMin + hoverPos.xRatio * (logMax - logMin));
        const hoverNote = getClosestNote(hoverFreq);

        ctx.strokeStyle = 'rgba(255, 255, 255, 0.2)';
        ctx.lineWidth = 1;
        ctx.setLineDash([4, 4]);

        ctx.beginPath(); ctx.moveTo(hX, 0); ctx.lineTo(hX, canvas.height); ctx.stroke();
        ctx.beginPath(); ctx.moveTo(0, hY); ctx.lineTo(canvas.width, hY); ctx.stroke();
        ctx.setLineDash([]);

        ctx.strokeStyle = 'rgba(56, 189, 248, 0.8)';
        ctx.lineWidth = 1.5;
        ctx.beginPath(); ctx.arc(hX, hY, 8, 0, Math.PI * 2); ctx.stroke();

        ctx.fillStyle = '#38bdf8';
        ctx.font = 'bold 12px sans-serif';
        ctx.textAlign = hX > canvas.width - 110 ? 'right' : 'left';
        ctx.fillText(`${hoverNote.name} (${hoverFreq.toFixed(1)} Hz)`, hX + (hX > canvas.width - 110 ? -12 : 12), hY - 10);
    }

    const activeKeys = Object.keys(activeVoices);
    if (activeKeys.length > 0) {
        let textInfo = [];
        const timeNow = performance.now() * 0.005;

        activeKeys.forEach(id => {
            const v = activeVoices[id];
            const x = normToCanvasX(v.xRatio);
            const y = normToCanvasY(v.yRatio);

            ctx.strokeStyle = `rgba(56, 189, 248, ${0.4 + v.yRatio * 0.6})`;
            ctx.lineWidth = 2;
            ctx.beginPath();
            for (let i = 0; i < canvas.width; i++) {
                const amp = (v.yRatio * 60) * zY;
                const waveY = (canvas.height / 2) + Math.sin((i + x + timeNow * 50) * 0.04) * amp * (1 - Math.abs(i - x) / canvas.width);
                if (i === 0) ctx.moveTo(i, waveY);
                else ctx.lineTo(i, waveY);
            }
            ctx.stroke();

            ctx.strokeStyle = '#d97706';
            ctx.lineWidth = 1.5;
            ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke();

            ctx.fillStyle = '#ffffff';
            ctx.beginPath(); ctx.arc(x, y, 7, 0, Math.PI * 2); ctx.fill();

            const closestNote = getClosestNote(v.freq);
            textInfo.push(`${closestNote.name}`);
        });

        const chordStatus = activeChordType ? ` | Acorde: ${document.getElementById('rootSelect').value}${chordOctave} ${activeChordType}` : '';
        info.innerText = `Tocando: [ ${textInfo.join(' + ')} ]${chordStatus}`;
    } else if (activeChordType) {
        info.innerText = `Acorde Sostenido: ${document.getElementById('rootSelect').value}${chordOctave} ${activeChordType}`;
    } else if (hoverPos.active) {
        const logMin = Math.log(minFreq);
        const logMax = Math.log(maxFreq);
        const hoverFreq = Math.exp(logMin + hoverPos.xRatio * (logMax - logMin));
        const hoverNote = getClosestNote(hoverFreq);
        info.innerText = `Vista previa: ${hoverNote.name} (${hoverFreq.toFixed(2)} Hz) | Vol: ${Math.round(hoverPos.yRatio * 100)}%`;
    } else {
        info.innerText = "Pad Numérico: [0=C, 1=C#, 2=D, 3=D#, 4=E, 5=F, 6=F#, 7=G, 8=G#, 9=A, ==A#, /=B, *=Oct+, Enter=REC]";
    }
}

window.onkeydown = (e) => {
    const key = e.key.toLowerCase();

    if (e.code === 'NumpadEnter') {
        e.preventDefault();
        toggleRecordLoop();
        return;
    }

    if (e.key === 'Enter') {
        e.preventDefault();
        togglePlayLoop();
        return;
    }

    if (e.key === 'ArrowUp') { e.preventDefault(); adjustThereminVolume(0.05); return; }
    if (e.key === 'ArrowDown') { e.preventDefault(); adjustThereminVolume(-0.05); return; }
    if (e.key === 'ArrowRight') { e.preventDefault(); adjustChordVolume(0.05); return; }
    if (e.key === 'ArrowLeft') { e.preventDefault(); adjustChordVolume(-0.05); return; }

    if (e.key === ',' || e.key === '<') { e.preventDefault(); changeKeysOctave(-1); return; }
    if (e.key === '.' || e.key === '>') { e.preventDefault(); changeKeysOctave(1); return; }

    const rawChar = e.key.replace('Numpad', '');
    if (customNumpadMap[rawChar]) {
        e.preventDefault();
        const select = document.getElementById('rootSelect');
        select.value = customNumpadMap[rawChar];
        updateChord();
        return;
    }

    if (e.code === 'NumpadMultiply' || e.key === '*') { e.preventDefault(); changeChordOctave(1); return; }
    if (e.code === 'NumpadAdd' || e.key === '+') { e.preventDefault(); changeChordOctave(1); return; }
    if (e.code === 'NumpadSubtract' || e.key === '-') { e.preventDefault(); changeChordOctave(-1); return; }

    if (e.key === 'Shift') { e.preventDefault(); toggleKeyChordMode(); return; }
    if (e.code === 'Space' || e.key === ' ') { e.preventDefault(); stopAll(); return; }

    if (keyToChordMap[key]) {
        e.preventDefault();
        toggleChord(keyToChordMap[key]);
        return;
    }

    if (keyboardPianoMap[key]) {
        e.preventDefault();
        const mapped = keyboardPianoMap[key];

        if (keyFollowsChord) {
            const select = document.getElementById('rootSelect');
            select.value = mapped.note;
            updateChord();
        } else if (!e.repeat) {
            const targetOctave = keysOctave + mapped.octaveOffset;
            const targetNoteName = `${mapped.note}${targetOctave}`;
            const noteTarget = notesList.find(n => n.name === targetNoteName);
            if (noteTarget) {
                startVoice(key, noteTarget.xRatio, 0.8);
            }
        }
        return;
    }
};

window.onkeyup = (e) => {
    const key = e.key.toLowerCase();
    if (keyboardPianoMap[key] && !keyFollowsChord) {
        stopVoice(key);
    }
};

let isMouseDown = false;

function getMousePos(e) {
    const rect = canvas.getBoundingClientRect();
    const canvasX = (e.clientX - rect.left) * (canvas.width / rect.width);
    const canvasY = (e.clientY - rect.top) * (canvas.height / rect.height);

    return {
        xRatio: Math.max(0, Math.min(1, canvasToNormX(canvasX))),
        yRatio: canvasToNormY(canvasY)
    };
}

canvas.onmousemove = (e) => {
    const pos = getMousePos(e);
    hoverPos = { xRatio: pos.xRatio, yRatio: pos.yRatio, active: true };

    if (isMouseDown) {
        startVoice('mouse', pos.xRatio, pos.yRatio);
    } else {
        triggerRedraw();
    }
};

canvas.onmouseleave = () => {
    hoverPos.active = false;
    if (!isMouseDown) triggerRedraw();
};

canvas.onmousedown = (e) => {
    isMouseDown = true;
    const pos = getMousePos(e);
    startVoice('mouse', pos.xRatio, pos.yRatio);
};

window.onmouseup = () => {
    if (isMouseDown) {
        isMouseDown = false;
        stopVoice('mouse');
    }
};

onZoomChange();
updateMasterFX();
</script>

</body>
</html>
"""

HTML(pantalla_html)